topics = {
    ('hangman 1') : 'The Basics',
    ('hangman 2') : 'Making Decisions',
    ('pyramid') : 'Repeating Instructions',
    ('hangman 3') : 'Repeating Instructions',
    ('outline') : 'Structuring Data',
    ('mastermind 1') : 'Structuring Data',
    ('toy robot 1') : 'Procedures',
    ('mastermind 2') : 'Procedures',
    ('mastermind 3') : 'Simple Compute',#
    ('recursion') : 'Calling Functions',
    ('toy robot 2') : 'Calling Functions',
    ('word processing') : 'Processing Collections',
    ('toy robot 3') : 'Processing Collections',
    ('accounting app') : 'Modules & Packages',
    ('toy robot 4') : 'Modules & Packages',
    ('toy robot 5') : 'Modules & Packages',
    ('fix the bugs') : "Don't Panic",
    ('code clinic booking system') : 'Group Project',
}